- README.md
And some minor heading level changes
> Clarify auth scheme

- go.mod
- go.sum
> go.mod: update neofs-api-go to 1.26.0

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- app.go
- downloader/download.go
- go.mod
- main.go
- neofs/client-plant.go
- settings.go
- uploader/upload.go
Replaced http-gate in files by http-gw.
> Replace http-gate by http-gw

- app.go
- downloader/download.go
- go.mod
- go.sum
- uploader/upload.go
Depends on nspcc-dev/neofs-sdk-go#6
> *: update to use unneofsed sdk-go

- README.md
> [#53] Fixed bearer cookie key in README.md

- README.md
> [#54] Bearer token generation example

- README.md
> [#59] Added Bearer token requirements

- README.md
- app.go
- go.mod
- go.sum
- settings.go
> [#60] Dropped grpc keepalive options

- downloader/download.go
- go.mod
- go.sum
- uploader/upload.go
> [#63] Using client.Object from sdk

- downloader/download.go
> [#65] Supported object Content-Type

- downloader/download.go
- downloader/reader_test.go
- go.mod
- go.sum
> [#67] Added streaming to download

- README.md
- settings.go
> [#71] Fix yaml config support

- app.go
> [#77] Added requests logging

- go.mod
- go.sum
> [#82] Update sdk-go

- README.md
- app.go
- downloader/download.go
- settings.go
> [#96] Add zip compression

- integration_test.go
> [#94] Fix multiple testcontainer images

- app.go
- downloader/download.go
- downloader/head.go
- metrics.go
- pprof.go
- response/utils.go
- uploader/upload.go
> [#105] Add newline to errors

- README.md
- go.mod
- uploader/filter.go
- uploader/filter_test.go
- uploader/upload.go
> [#108] Add different expiration header formats

- CONTRIBUTING.md
- README.md
> [#120] Fix project name

- README.md
- downloader/download.go
Closes #123 
Made requests for objects by attribute url-encoded.
> [#123] Add url-encoded queries for attr values

- downloader/download.go
- downloader/head.go
> [#125] Use the same HEAD, GET headers formation

- downloader/download.go
- downloader/head.go
- downloader/reader_test.go
Signed-off-by: Leonard Lyubich <leonard@nspcc.ru>
> downloader: Simplify detecting the Content-Type from payload

- app.go
- downloader/download.go
- downloader/head.go
- go.mod
- go.sum
- integration_test.go
- uploader/upload.go
> [#139] Update SDK

- README.md
- app.go
- config/config.env
- config/config.yaml
- settings.go
> [#140] Improve docs

- downloader/download.go
- uploader/upload.go
> [#144] Add more verbose error output

- CONTRIBUTING.md
- README.md
- downloader/download.go
- misc.go
- tokens/bearer-token.go
- uploader/filter.go
Checked for some inaccuracies regarding English.
Signed-off-by: Elizaveta Chichindaeva <elizaveta@nspcc.ru>
> English Check

- README.md
- app.go
- config/config.env
- config/config.yaml
- downloader/download.go
- downloader/head.go
- go.mod
- go.sum
- integration_test.go
- resolver/neofs.go
- resolver/resolver.go
- settings.go
- tokens/bearer-token.go
- tokens/bearer-token_test.go
- uploader/upload.go
- utils/params.go
- utils/util.go
> [#142] Support container resolver

- Makefile
- tokens/bearer-token.go
> [#161] Fix lint

- .github/workflows/codeql-analysis.yml
> [#158] Update CodeQL action to v2

- .github/workflows/builds.yml
- .github/workflows/tests.yml
- CHANGELOG.md
> Release v0.21.0

- README.md
- docs/gate-configuration.md
- settings.go
> [#172] Describe configuration

- app.go
- metrics.go
> [#175] Add health metric

- Makefile
It is enabled by default since go1.16
> Drop GO111MODULE from builds

- app.go
- config/config.env
- config/config.yaml
- docs/gate-configuration.md
- settings.go
> [#184] Add config param for pool error threshold

- app.go
- metrics/metrics.go
Based on and blocked by #181
close #179
> [#179] Expose pool metrics

- Makefile
Signed-off-by: anikeev-yadro <a.anikeev@yadro.com>
> [#190] Filter version tags for version calculation

- main.go
- uploader/multipart/multipart.go
> [#191] Fix lint issues

- README.md
> [#189] Mention NNS in README

- go.mod
- go.sum
> [#196] Update sdk

- .github/workflows/builds.yml
- .github/workflows/tests.yml
- Dockerfile
- Makefile
> [#197] Update go version to 1.19

- Makefile
Signed-off-by: Alex Vanin <a.vanin@yadro.com>
> Fix commit abbrev length in version

- CHANGELOG.md
> [#204] Fix changelog section

- CHANGELOG.md
- app.go
- downloader/download.go
- integration_test.go
- main.go
- metrics/metrics.go
- resolver/resolver.go
- settings.go
- uploader/upload.go
- utils/util.go
This PR reload the following things on `SIGHUP`:
* log level
* prometheus/pprof services
* resolvers order 
* `defaultTimestamp` parameter
* zip compression 
close #200
> Support config reload on  SIGHUP

- downloader/download.go
> [#206] Refactor neofs 'not found' errors

- .github/workflows/builds.yml
- go.mod
> [#209] Add check dirty version to CI

- docs/gate-configuration.md
> [#208] Add SIGHUP docs

- downloader/head.go
> [#218] Unify system attribute format for GET/HEAD

- CHANGELOG.md
- README.md
- downloader/download.go
- integration_test.go
Skip objects with invalid FilePath
close #222 
> [#222] Fix zip streaming

- README.md
> [#215] Mention caching strategy in README.md

- CHANGELOG.md
- app.go
- config/config.env
- config/config.yaml
- docs/gate-configuration.md
- go.mod
- go.sum
- settings.go
> [#234] Update SDK to support timeout for stream

- config/config.env
> [#236] Fix config example

- CHANGELOG.md
- app.go
- config/config.env
- config/config.yaml
- docs/gate-configuration.md
- integration_test.go
- server.go
- settings.go
closes #228 
Signed-off-by: Pavel Pogodaev <p.pogodaev@yadro.com>
> [#228] add support of multiple addresses

- CHANGELOG.md
- integration_test.go
- uploader/filter.go
- uploader/filter_test.go
- uploader/upload.go
Signed-off-by: Artem Tataurov <a.tataurov@yadro.com>
> [#221] add error response on key duplicates

- .golangci.yml
- CHANGELOG.md
> [#239] Remove deprecated linters

- app.go
- metrics/metrics.go
> Add version metric

- .github/workflows/dco.yml
Sharing the code is better than duplicating it.
> workflows: update dco to org-wide one

- .github/workflows/builds.yml
- .github/workflows/tests.yml
- Dockerfile
- Makefile
- downloader/download.go
- go.mod
- go.sum
- uploader/upload.go
> Upgrade to go 119

- .github/workflows/system-tests.yml
Do not merge beore https://github.com/nspcc-dev/neofs-testcases/pull/677
> Remove Modify venv patch
