nspcc-dev/neofs-http-gw

downloader/download.go
uploader/upload.go

It's enough to do the job, we don't really need full client.Client interface
here.
Signed-off-by: Roman Khimov <roman@nspcc.ru>

*: use client.Object where appropriate

---

downloader/download.go

It should never ever be sent in local time, instead of
Last-Modified: Tue, 29 Jun 2021 12:02:57 MSK
one should receive
Last-Modified: Tue, 29 Jun 2021 09:02:57 GMT
Signed-off-by: Roman Khimov <roman@nspcc.ru>

downloader: fix Last-Modified header

---

README.md
app.go
downloader/download.go
downloader/head.go

[#76] Added HEAD methods

---

downloader/download.go

[#30] Fix not found responses

---

integration_test.go

neofs-node v0.26.1 release tracks session token expiration more closely, so it has to be specified correctly.
Merge after https://github.com/nspcc-dev/neofs-aio/pull/8

test: Set up pool with SessionExpiration value

---

app.go

Closes #109 
Also fixed print of version in --help and --version. Earlier default version `dev` has been always printed in responses to these commands. Now we print the following way: 
- if version is set in env : `-v` and `-h` print the value from env
- if config is set and env is not: `-v` prints config version, `-h` -- default version (because we print default `Default environments` in help.
- If neither env nor config are set: dev in `-v` and `-h`.

[#109] GW version

---

downloader/download.go
downloader/download_test.go
downloader/head.go
uploader/filter.go
uploader/filter_test.go
uploader/upload.go
utils/attributes.go

Closes #111
Also moved attribute/headers constants to a separate file `util/attributes.go`. I'm not sure that the name is correct/good enough,  but I have no better idea about the name.

[#11] Fix headers format

---

integration_test.go

Race condition checks are suitable for unit tests
but mostly useless in case of full-size integration
test with neofs-all-in-one test container.
Should fix fail of data coverage action.

Remove race condition check in integration test

---

README.md

Since Go 1.16, go install can install a command at a version specified on the command line while. Starting in Go 1.17, installing executables with go get is deprecated.

Replace `go get` with `go install`

---

README.md
config/config.env
config/config.yaml
settings.go

10 minute upload and 5 minute download timeouts are long enough
to handle average size objects in the real networks. For big
data streams these timeouts should be disabled.
Closes #146

Update default values for HTTP_GW_READ/WRITE_TIMEOUT

---

app.go
downloader/download.go
downloader/head.go
uploader/upload.go

It is meaningless to use RequestCtx as a context.Context
for NeoFS operation, because context won't be closed
until application shutdown. Moreover, it also triggers
data race detection, because server's done channel, which
is accessible for reading from RequestCtx, is set to `nil`.
Using application context doesn't change gateway behavior,
but it suppresses data race trigger at shutdown. It also
allows possibility to set configurable timeouts for NeoFS
networking if we will ever need them.

Use application context in NeoFS API requests 

---

downloader/download.go
integration_test.go

Declined to use `(*zip.Writer).CreateRaw()` as it does not result in a noticeable performance increase, but introduces unnecessary complexity.
Increased buffer to download zip archive up to 3MB (the same as for upload files).
Started using `(*fasthttp.RequestCtx).SetBodyStreamWriter()` to get rid of of accumulation of response body in application memory.
close #163 

[#163] Fix zip streaming

---

app.go
settings.go

Will fix numbers in commits later

Wallet config

---

metrics/metrics.go

Since pool statistic contains current values rather than delta we should use gauge metric.

[#194] Use gauge instead of counter for metrics

---

CHANGELOG.md
uploader/filter.go
uploader/filter_test.go

Previous implementation does not provide 'at least' lifetime guarantee.
Implementation is taken from [neofs-s3-gw](https://github.com/nspcc-dev/neofs-s3-gw/blob/272c4857062eeba8728333c16f3c88e51e7d8d3a/internal/neofs/neofs.go#L55)
Related to https://github.com/nspcc-dev/neofs-node/issues/1670
According to specification, expiration epoch is last epoch when object is available. We set expiration epoch such way that it crosses lifetime limit. Next epoch after will remove an object. 
```
current epoch: 23 (1h has passed)
epoch duration: 1.5h
lifetime: 4h
delta => 4h / 1.5h = 2.6 ~ 3.0
exp = 23 + 3 = 26
| wall time | epoch | 
|   0.0h    |  23   | <- object upload here after 1h of 23rd epoch with expectation of 4h lifetime
|   0.5h    |  24   | 
|   2.0h    |  25   | <- previous implementation …
```

Fix expiration epoch calculation

---

.github/workflows/tests.yml

We should definitely have tests running on the version of go from go.mod.

[#202] Return go1.17 to CI tests

---

Makefile
help.mk

Now it prints: 
```
$ make help
Usage:
make <target>
Targets:
all             Make all binaries
clean           Clean up
cover           Run tests with race detection and produce coverage output
dep             Pull go dependencies
dirty-image     Build dirty Docker image
docker/lint     Run linters in Docker
docker/%        Run `make %` in Golang container, for more information run `make help.docker/%`
fmt             Reformat code
help            Show this help prompt
image           Build clean Docker image
image-push      Push Docker image to the hub
lint            Run linters
test            Run tests
version         Print version
$ make help.docker/%
Usage:
make docker/% -- Run `make %` in Golang container
Supported docker targets:
all
lint
bin/neofs-http-gw
```

[#213] Makefile: Add help

---

downloader/download.go
integration_test.go

Fix segfaults

---

metrics/metrics.go

reference #248
I have no idea how I checked it before, but without this row, Prometheus stats don't have required field with version

Add version metric fix

---

README.md
integration_test.go
metrics/metrics.go
uploader/multipart.go
uploader/multipart/multipart.go
uploader/multipart_test.go
uploader/upload.go

It makes sense in general (since HTTP Content-Type is multipart/form) and browsers usually set it. This will help to have a more secure send.fs.neo.org since explicit Content-Type is then always returned for GETs (otherwise it's autodetected).

uploader: respect Content-Type from MIME part header
